module.exports = {
  constants: {
    STATUS_ONLINE: "STATUS_ONLINE",
    STATUS_INVISIBLE: "STATUS_INVISIBLE",
    STATUS_IDLE: "STATUS_IDLE",
    STATUS_DO_NOT_DISTURB: "STATUS_DO_NOT_DISTURB",
    EN: "EN",
    OUTBOUND_REQUEST: "OUTBOUND_REQUEST",
    INBOUND_REQUEST: "INBOUND_REQUEST",
  },
};
